kind: Deployment
apiVersion: apps/v1
metadata:
  name: cloudevents-conductor
  labels:
    app: cloudevents-conductor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudevents-conductor
  template:
    metadata:
      labels:
        app: cloudevents-conductor
    spec:
      serviceAccountName: cloudevents-conductor-sa
      containers:
      - name: conductor
        image: quay.io/morvencao/conductor:latest
        imagePullPolicy: IfNotPresent
        args:
        - "grpc"
        - "--server-config=/etc/cloudevents-conductor/config/grpc-server-config.yaml"
        - "--disable-leader-election=true"
        - "--v=2"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
        volumeMounts:
          - name: cloudevents-conductor-config
            mountPath: "/etc/cloudevents-conductor/config"
            readOnly: true
          - name: grpc-server-certs
            mountPath: "/etc/cloudevents-conductor/certs"
            readOnly: true
        ports:
          - containerPort: 8090
            name: grpc
            protocol: TCP
      volumes:
      - name: cloudevents-conductor-config
        secret:
          secretName: cloudevents-conductor-config
      - name: grpc-server-certs
        secret:
          secretName: grpc-server-certs